const data = {
	name: 'Bildgenerierung',
	children: [
		{
			name: 'Motiv',
			children: [
				{
					name: 'Thema',
					id: 'thema-output',
					class: 'btn-outline-primary',
					type: 'button',
					children: [
						{ name: 'Ein mittelalterliches Schloss', description: 'Test' },
						{ name: 'Ein futuristisches Raumschiff' },
						{ name: 'Eine Landschaft mit Wasserfällen' },
						{ name: 'Landschaft' },
						{ name: 'Portrait' },
						{ name: 'Abstrakt' },
						{ name: 'Stilleben' },
						{ name: 'Aktion' },
						{ name: 'Sport' },
						{ name: 'Fantasy' },
						{ name: 'Historisch' },
						{ name: 'Futuristisch' },
						{ name: 'Dystopisch' },
						{ name: 'Utopisch' },
						{ name: 'Industriell' },
						{ name: 'Aquatisch' },
					],
				},
				{
					name: 'Elemente',
					id: 'elemente-output',
					class: 'btn-outline-primary',
					type: 'button',
					children: [
						{ name: 'Bäume' },
						{ name: 'Gebäude' },
						{ name: 'Menschen' },
						{ name: 'Tiere' },
						{ name: 'Fahrzeuge' },
						{ name: 'Möbel' },
						{ name: 'Geräte' },
						{ name: 'Wolken' },
						{ name: 'Gewässer' },
						{ name: 'Berge' },
						{ name: 'Blumen' },
						{ name: 'Früschte' },
						{ name: 'Elektronik' },
						{ name: 'Denkmäler' },
						{ name: 'Wege' },
						{ name: 'Straßen' },
					],
				},
				{
					name: 'Komposition & Perspektive',
					id: 'komposition-output',
					class: 'btn-outline-primary',
					type: 'button',
					children: [
						{ name: 'Nahaufnahme' },
						{ name: 'Augenhöhe' },
						{ name: 'tiefer Winkel' },
						{ name: 'hoher Winkel' },
						{ name: 'Fisheye' },
						{ name: 'Über die Schulter' },
						{ name: 'Zentrale Positionierung des Hauptmotivs' },
						{ name: 'Angedeutete Führungslinien' },
						{ name: 'Asymmetrische Bildaufteilung' },
						{ name: 'Außermittig' },
						{ name: 'Close-Up' },
						{ name: 'Diagonale Führungslinien' },
						{ name: 'Einrahmung durch Schatten' },
						{ name: 'Einrahmung durch Silhouette' },
						{ name: 'Eye-Level' },
						{ name: 'Froschperspektive' },
						{ name: 'Führungslinien' },
						{ name: 'Goldener Schnitt' },
						{ name: 'Horizontale Führungslinien' },
						{ name: 'Komposition durch Ebenen' },
						{ name: 'Künstlicher Rahmen' },
						{ name: 'Natürlicher Rahmen' },
						{ name: 'Panorama-Aufnahme' },
						{ name: 'Schnappschuss' },
						{ name: 'Senkrechte Führungslinien' },
						{ name: 'Sich wiederholende Führungslinien' },
						{ name: 'Symmetrische Bildaufteilung' },
						{ name: 'Unausgeglichene Komposition' },
						{ name: 'Vogelperspektive' },
						{ name: 'Zwei-Drittel-Regel' },
					],
				},
				{
					name: 'Szeneneinstellung',
					id: 'szeneneinstellung-output',
					class: 'btn-outline-primary',
					type: 'button',
					children: [
						{ name: 'Dichte Nebelwälder' },
						{ name: 'Eine pulsierende Großstadt' },
						{ name: 'Ein abgelegener Sandstrand' },
						{ name: 'draußen' },
						{ name: 'drinnen' },
						{ name: 'Urban' },
						{ name: 'ländlich' },
						{ name: 'Küste' },
						{ name: 'bergig' },
						{ name: 'Wüste' },
						{ name: 'Dschungel' },
						{ name: 'Fluss' },
						{ name: 'Insel' },
						{ name: 'unter Wasser' },
						{ name: 'Luftaufnahme' },
						{ name: 'unterirdisch' },
						{ name: 'außerirdisch' },
					],
				},
			],
		},
		{
			name: '',
			id: 'stil-output',
			class: 'btn-outline-secondary',
			type: 'button',
			children: [
				{
					name: 'Abstrakt',
					description: 'Fokus auf Farben, Formen und Strukturen statt auf konkrete Gegenstände oder Szenen.',
				},
				{
					name: 'Anime-Stil',
					description: 'Lebhafte, gezeichnete Darstellungen im Stil japanischer Animation.',
				},
				{
					name: 'Architekturfotografie',
					description: 'Gebäude und urbane Strukturen in ästhetischen und geometrischen Kompositionen.',
				},
				{
					name: 'Astrofotografie',
					description: 'Fotografien des Nachthimmels, oft mit Fokus auf Sterne, Planeten und Galaxien.',
				},
				{
					name: 'Barock',
					description: 'Prunkvolle, detailreiche Darstellungen, oft mit intensiven Farben und Goldakzenten.',
				},
				{
					name: 'Bewegungsunschärfe',
					description:
						'CM (Intentional Camera Movement) bezeichnet eine Fototechnik, bei der durch bewusstes Bewegen der Kamera während einer längeren Belichtungszeit gezielt unscharfe, abstrakte Bilder entstehen.',
				},
				{
					name: 'Boudoir',
					description: 'Intime, elegante Portraits, oft mit romantischer und sinnlicher Stimmung.',
				},
				{
					name: 'Cartoon',
					description: 'Übertriebene, humorvolle Formen mit satten Farben und vereinfachten Designs.',
				},
				{
					name: 'Cinematisch',
					description: 'Filmähnliche Ästhetik mit Fokus auf Licht, Farben und Erzählung.',
				},
				{
					name: 'Concept Art',
					description:
						'Künstlerische Darstellungen, die Ideen oder Konzepte visualisieren, häufig in der Film- oder Spieleindustrie genutzt.',
				},
				{
					name: 'Cyberpunk',
					description: 'Futuristische, neonlastige Ästhetik, oft mit düsteren und technologischen Elementen.',
				},
				{
					name: 'Dokumentarisch',
					description: 'Authentische, ungefilterte Darstellung des Lebens, oft mit gesellschaftlichem Fokus.',
				},
				{
					name: 'Doppelbelichtung',
					description: 'meherer Bilder übereinander gelegt',
				},
				{
					name: 'Dramatisch',
					description:
						'Ein dramatisches Bild erzeugt starke Emotionen und Spannung durch Kontraste, Licht, Perspektive und ausdrucksstarke Motive.',
				},
				{
					name: 'Drohnenfotografie',
					description: 'Luftaufnahmen mit einzigartigen Perspektiven, oft aus großer Höhe.',
				},
				{
					name: 'Editorial',
					description: 'Künstlerische Fotografien, oft für Zeitschriften oder Storytelling.',
				},
				{
					name: 'Expressionistisch',
					description: 'Intensiv und emotional, mit starken Farben und dramatischen Kompositionen.',
				},
				{
					name: 'Fantasy',
					description: 'Magische und fantastische Szenen, oft mit kreativen und übernatürlichen Elementen.',
				},
				{
					name: 'Fine Art',
					description: 'Künstlerisch und oft abstrakt, mit Fokus auf Ästhetik und Emotionen.',
				},
				{
					name: 'Fotorealistisch',
					description:
						'beschreibt Bilder, die so detailgetreu und präzise dargestellt sind, dass sie wie echte Fotografien wirken',
				},
				{
					name: 'Food-Fotografie',
					description: 'Ästhetische Darstellung von Speisen und Getränken, oft mit Fokus auf Textur und Farbe.',
				},
				{
					name: 'Futuristisch',
					description: 'Szenen mit futuristischen Technologien, Räumen und Designs, die in die Zukunft blicken.',
				},
				{
					name: 'Gothic',
					description: 'Dunkel und mystisch, oft mit dramatischem Licht und architektonischen Details.',
				},
				{
					name: 'High-Key',
					description: 'Helle und lebhafte Bilder mit wenig Schatten, oft für eine luftige Stimmung.',
				},
				{
					name: 'Hyperrealistisch',
					description: 'So detailliert und lebensecht, dass es fast über die Realität hinausgeht.',
				},
				{
					name: 'Impressionistisch',
					description:
						'Weiche, lichtdurchflutete Darstellungen mit Fokus auf Atmosphäre und Emotionen statt auf Details.',
				},
				{
					name: 'Industrial',
					description: 'Fokus auf Fabriken, Maschinen und industrielle Umgebungen, oft mit rauer Ästhetik.',
				},
				{
					name: 'Kawaii',
					description: 'Niedliche, verspielte Darstellungen, oft mit sanften Farben und süßen Details.',
				},
				{
					name: 'Kinderfotografie',
					description: 'Emotionale und lebendige Darstellungen von Kindern, oft in spielerischen Szenen.',
				},
				{
					name: 'Landschaftsfotografie',
					description: 'Darstellung von Natur- und Außenlandschaften, oft mit Schwerpunkt auf Licht und Perspektive.',
				},
				{
					name: 'Langzeitbelichtung',
					description:
						'ist eine Aufnahmetechnik, bei der der Verschluss der Kamera für eine längere Zeit geöffnet bleibt, um Bewegungen sichtbar zu machen oder Lichtspuren einzufangen',
				},
				{
					name: 'Low-Key',
					description: 'Dunkle, stimmungsvolle Bilder mit betontem Schatten und Licht.',
				},
				{
					name: 'Makrofotografie',
					description: 'Extrem detaillierte Nahaufnahmen von kleinen Objekten oder Strukturen.',
				},
				{
					name: 'Melancholisch',
					description:
						'beschreibt einen Zustand der sanften Traurigkeit oder Nachdenklichkeit, oft verbunden mit Sehnsucht und stiller Wehmut',
				},
				{
					name: 'Minimalistisch',
					description: 'Einfachheit und Reduktion auf das Wesentliche, oft mit viel Negativraum.',
				},
				{
					name: 'Modefotografie',
					description: 'Darstellung von Kleidung und Accessoires, oft in kreativen und stilisierten Szenen.',
				},
				{
					name: 'Noir',
					description:
						'Kontrastreiche Schwarz-Weiß-Ästhetik, oft mit stimmungsvollen Schatten und geheimnisvollem Flair.',
				},
				{
					name: 'Panoramafotografie',
					description: 'Breite, detaillierte Aufnahmen von Landschaften oder Stadtansichten.',
				},
				{
					name: 'Piktorialismus',
					description:
						'Der Piktorialismus ist ein fotografischer Stil, der durch weiche Fokussierung, malerische Ästhetik und handwerkliche Manipulation versucht, die Fotografie als Kunstform zu etablieren und Emotionen statt dokumentarischer Genauigkeit in den Vordergrund zu stellen.',
				},
				{
					name: 'Portrait',
					description: 'Fokus auf die Darstellung von Menschen, oft mit Betonung von Emotionen und Persönlichkeit.',
				},
				{
					name: 'Postapokalyptisch',
					description:
						'Szenarien nach einer Katastrophe, oft düster, mit verfallenen Gebäuden und überwucherten Landschaften.',
				},
				{
					name: 'Produktfotografie',
					description: 'Darstellung von Produkten für Werbung, mit besonderem Fokus auf Details und Beleuchtung.',
				},
				{
					name: 'Psychedelisch',
					description: 'Lebhafte, verzerrte und farbenfrohe Szenen, die an Träume oder Halluzinationen erinnern.',
				},
				{
					name: 'Realistisch',
					description:
						'Darstellung von Szenen, die der Realität so nah wie möglich kommen, ohne künstlerische Verzerrung.',
				},
				{
					name: 'Reise',
					description: 'Bilder, die verschiedene Kulturen, Orte und Abenteuer dokumentieren.',
				},
				{
					name: 'Retro',
					description:
						'Nostalgischer Stil, der auf vergangene Jahrzehnte anspielt, oft mit Vintage-Farbpaletten und Elementen.',
				},
				{
					name: 'Romantisch',
					description:
						'beschreibt etwas, das Gefühle von Liebe, Sehnsucht oder Harmonie weckt und oft mit Schönheit, Zärtlichkeit oder idealisierten Vorstellungen verbunden ist.',
				},
				{
					name: 'Schwarz-Weiß',
					description: 'Monochrome Ästhetik, die Kontraste und Strukturen betont.',
				},
				{
					name: 'Skizzenhaft',
					description: 'Wie eine Zeichnung oder Skizze, oft mit klaren Linien und Schraffuren.',
				},
				{
					name: 'Sportfotografie',
					description: 'Dynamische Aufnahmen von Sportereignissen mit Fokus auf Bewegung und Energie.',
				},
				{
					name: 'Steampunk',
					description: 'Retro-futuristischer Stil, inspiriert von viktorianischer Ästhetik und Dampfmaschinen.',
				},
				{
					name: 'Stillleben',
					description: 'Arrangierte Objekte, oft mit künstlerischem Fokus auf Licht und Schatten.',
				},
				{
					name: 'Street Art Style',
					description: 'Inspiriert von Graffiti und urbaner Kunst, mit intensiven Farben und Formen.',
				},
				{
					name: 'Street Photography',
					description: 'Spontane Szenen aus dem urbanen Alltag, oft dynamisch und ungestellt.',
				},
				{
					name: 'Surrealistisch',
					description: 'Traumhafte, oft unwirkliche Szenen mit fantastischen Elementen und unerwarteten Kompositionen.',
				},
				{
					name: 'Unterwasserfotografie',
					description: 'Szenen unter Wasser, oft mit besonderem Fokus auf Lichtbrechung und Farben.',
				},
				{
					name: 'Vintage',
					description: 'Alte, nostalgische Ästhetik mit oft entsättigten Farben und körniger Textur.',
				},
				{
					name: 'Wildlife',
					description: 'Aufnahmen von Tieren in freier Wildbahn, mit Fokus auf Verhalten und Umgebung.',
					tag: ['natur', 'grün'],
				},
			],
		},
		{
			name: 'Beleuchtung',
			children: [
				{
					name: 'Richtung des Lichtes',
					id: 'richtung-output',
					class: 'btn btn-outline-info',
					type: 'button',
					children: [
						{ name: 'von oben' },
						{ name: 'von unten' },
						{ name: 'seitlich' },
						{ name: 'frontal' },
						{ name: 'Rücklicht' },
						{ name: 'Diffus' },
						{ name: 'gemischt' },
						{ name: 'Kreuzlicht' },
						{ name: 'zerstreut' },
						{ name: 'fokussiert' },
						{ name: 'schmal' },
					],
				},
				{
					name: 'Lichtintensität',
					id: 'intensitaet-output',
					class: 'btn btn-outline-info',
					type: 'button',
					children: [
						{ name: 'Weiches Morgenlicht' },
						{ name: 'Dramatisches Gegenlicht' },
						{ name: 'Schummriges Kerzenlicht' },
						{ name: 'Hoher Kontrast' },
						{ name: 'Hohes Detailniveaut' },
						{ name: 'HDR' },
						{ name: 'Hohes Maß an Dynamik' },
						{ name: 'Natürliches Licht' },
						{ name: 'Starke Farbkontraste' },
						{ name: 'Gegenlicht' },
						{ name: 'hartes Licht' },
					],
				},
			],
		},
		{
			name: 'Farbpalette',
			children: [
				{
					name: 'Stimmung',
					id: 'stimmung-output',
					class: 'btn btn-outline-success',
					type: 'button',
					children: [
						{ name: 'hell' },
						{ name: 'dunkel' },
						{ name: 'kalt' },
						{ name: 'warm' },
						{ name: 'neutral' },
						{ name: 'Friedlich und beruhigend' },
						{ name: 'Düster und geheimnisvoll' },
						{ name: 'Fröhlich und lebendig' },
						{ name: 'Nostalgisch' },
						{ name: 'dunkel und mystisch' },
						{ name: 'düster' },
						{ name: 'dramatisch' },
						{ name: 'verspielt' },
					],
				},
				{
					name: 'Töne',
					id: 'ton-output',
					class: 'btn btn-outline-success',
					type: 'button',
					children: [
						{ name: 'Pastell' },
						{ name: 'Lebhaft' },
						{ name: 'Gedämpft' },
						{ name: 'Gesättigt' },
						{ name: 'Entsättigt' },
						{ name: 'Monochromatisch' },
						{ name: 'Komplementär' },
					],
				},
				{
					name: 'Farbe',
					id: 'farbe-output',
					class: 'btn btn-outline-success',
					type: 'button',
					children: [
						{ name: 'blau' },
						{ name: 'silber' },
						{ name: 'kalt' },
						{ name: 'warm' },
						{ name: 'neutral' },
						{ name: 'bernstein' },
						{ name: 'sepia' },
						{ name: 'Warme Herbstfarben', tag: ['natur'] },
						{ name: 'Schwarz-Weiß' },
						{ name: 'Pastelltöne' },
						{ name: 'Leuchtende Neonfarben' },
						{ name: 'kalte Farben' },
						{ name: 'Abenddämmerung' },
					],
				},
			],
		},
		{
			name: 'Bildbearbeitungsaufforderungen',
			children: [
				{
					name: 'Bereiche löschen wie z.B.',
					id: 'deleteElement-output',
					class: '',
					type: 'text',
					children: [{ name: 'Gebäude' }, { name: 'Menschen' }, { name: 'Fahrzeuge' }, { name: 'Schilder' }],
				},
				{
					name: 'Neue Elemente hinzufügen wie z.B.',
					id: 'addElement-output',
					class: '',
					type: 'text',
					children: [
						{ name: 'Bäume' },
						{ name: 'Tiere' },
						{ name: 'Wolken' },
						{ name: 'Sterne' },
						{ name: 'Mond' },
						{ name: 'Sonne' },
						{ name: 'Regen' },
						{ name: 'Schnee' },
						{ name: 'Nebel' },
						{ name: 'Regenbogen' },
						{ name: 'Blitze' },
						{ name: 'Blumen' },
						{ name: 'Vögel' },
					],
				},
				{
					name: 'Bestehende Elemente skalieren',
					id: 'scaleElement-output',
					class: '',
					type: 'text',
					children: [
						{ name: 'Gebäude verkleinern' },
						{ name: 'Menschen vergößern' },
						{ name: 'Fahrzeuge komprimieren' },
						{ name: 'Himmel erweitern' },
					],
				},
				{
					name: 'Zusätzliche Bilder überlagern',
					id: 'overlayImage-output',
					class: '',
					type: 'text',
					children: [
						{ name: 'Text' },
						{ name: 'Karte' },
						{ name: 'Effekte' },
						{ name: 'Muster' },
						{ name: 'Vintage-Filter' },
					],
				},
				{
					name: 'Farben ersetzen',
					id: 'changeColor-output',
					class: '',
					type: 'list',
					children: [
						{ name: 'Grün in Herbstfarben ändern' },
						{ name: 'Blau durch stürmisches Grau ersetzen' },
						{ name: 'Weiß mit Gold tauschen' },
					],
				},
				{
					name: 'Komposition anpassen',
					id: 'changeCompo-output',
					class: '',
					type: 'list',
					children: [
						{ name: 'Elemente neu positionieren' },
						{ name: 'Horizontal oder vertikal ausrichten' },
						{ name: 'Fokuspunkte zentrieren' },
						{ name: 'Asymmetrie ausgleichen' },
						{ name: 'Gleichmäßig verteilen' },
						{ name: 'Führende Linien schaffen' },
					],
				},
				{
					name: 'Texturen ändern',
					id: 'changeTextures-output',
					class: '',
					type: 'list',
					children: [
						{ name: 'Wasser glätten' },
						{ name: 'Gelände aufraue' },
						{ name: 'Glanz auf Oberflächen hinzufügen' },
						{ name: 'Mattierungen erzeugen' },
						{ name: 'Glitzer hinzufügen' },
					],
				},
				{
					name: 'Elemente mischen',
					id: 'mergeElement-output',
					class: '',
					type: 'list',
					children: [
						{ name: 'Himmel mit Horizont mischen' },
						{ name: 'Schatten mit Gelände verbinden' },
						{ name: 'Reflexionen ins Wasser einfügen' },
						{ name: 'Blattwerk mit Bäumen verschmelzen' },
					],
				},
				{
					name: 'Outpainting',
					id: 'outpainting-output',
					class: '',
					type: 'list',
					children: [
						{ name: 'Himmel nach oben erweitern' },
						{ name: 'Wald nach außen vergrößern' },
						{ name: 'Straße nach vorne verlängern' },
						{ name: 'Meerblick vergrößern' },
						{ name: 'Feld seitlich dehnen' },
					],
				},
			],
		},
		{
			name: 'Künstler/Inspiration',
			id: 'creator-output',
			class: '',
			type: 'link',
			children: [
				{
					name: 'Walt Disney',
					description: 'Cartoon, handgezeichneter Animationsstil',
					link: 'https://www.catawiki.com/nl/l/66533137-walt-disney-studios-disney-kunstwerk-framed-original-animation-drawing-additional-book-building-a-building',
				},
				{
					name: 'Banksy',
					description: 'Street Art, Schablonen-Graffiti, gesellschaftskritisch',
					link: 'https://www.singulart.com/de/blog/2023/11/17/beruehmte-banksy-gemaelde/',
				},
				{
					name: 'Pablo Picasso',
					description: 'Kubismus, abstrakte Formen, geometrische Darstellung',
					link: 'https://themuseum.blog/de/10-kunstwerke-von-picasso-die-sie-kennen-sollten/',
				},
				{
					name: 'Vincent van Gogh',
					description: 'Post-Impressionismus, expressive Pinselstriche, Farben',
					link: 'https://www.nga.gov/collection/highlights/van-gogh-self-portrait.html',
				},
				{
					name: 'Claude Monet',
					description: 'Impressionismus, Licht- und Farbenspiele',
					link: 'https://www.arthistoryproject.com/artists/claude-monet/sunset-on-the-seine-at-lavacourt-winter-effect/',
				},
				{
					name: 'Leonardo da Vinci',
					description: 'Renaissance, realistisches Zeichnen, sfumato-Technik',
					link: 'https://www.singulart.com/de/blog/2023/11/02/leonardo-da-vinci-gemaelde/',
				},
				{
					name: 'Salvador Dalí',
					description: 'Surrealismus, traumartige, verzerrte Bilder',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Frida Kahlo',
					description: 'Surrealismus, Selbstporträts, mexikanische Symbolik',
					link: 'https://www.kunstnet.org/werk/509693-frida-kahlo',
				},
				{
					name: 'Andy Warhol',
					description: 'Pop Art, Massenproduktion, Konsumkultur',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Jackson Pollock',
					description: 'Action Painting, Drip-Technik, abstrakter Expressionismus',
					link: 'https://www.artdex.com/myth-genius-jackson-pollock/',
				},
				{
					name: 'Keith Haring',
					description: 'Street Art, einfache Linien, lebendige Farben',
					link: 'https://www.npr.org/2023/05/27/1178084648/keith-haring-radiant-baby-the-broad',
				},
				{
					name: 'Henri Matisse',
					description: 'Fauvismus, kräftige Farben, vereinfachte Formen',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Gustav Klimt',
					description: 'Jugendstil, goldene Ornamente, dekorative Elemente',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Edvard Munch',
					description: 'Expressionismus, düstere Farben, emotionale Themen',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Hokusai',
					description: 'Japanische Ukiyo-e Kunst, Holzschnitte, „Die große Welle“',
					link: 'https://www.alamy.de/die-grosse-welle-von-kanagawa-katsushika-hokusai-1831-holzschnitt-drucken-aka-der-wave-japanische-kunst-image235761420.html',
				},
				{
					name: 'Yayoi Kusama',
					description: 'Avantgarde, psychedelische Punkte, Installationen',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Joan Miró',
					description: 'Surrealismus, abstrakte Formen, kindliche Symbole',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Albrecht Dürer',
					description: 'Renaissance, realistische Druckgrafik und Holzschnitte',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
				{
					name: 'Jean-Michel Basquiat',
					description: 'Neoexpressionismus, Graffiti-Einflüsse, rohe Energie',
					link: 'https://artlia.de/blogs/wandbilder-digest/die-20-beruhmtesten-maler-der-kunstgeschichte',
				},
			],
		},
		{
			name: 'Format/Dimensionen',
			description: 'Überlegen SIe sich, wie das Bildformat sein soll.',
			id: 'format-output',
			class: 'btn btn-outline-info',
			type: 'button',
			children: [
				{ name: 'Quadratisch (1:1)' },
				{ name: 'Panorama (16:9)' },
				{ name: 'Hochformat (3:4)' },
				{ name: 'Querformat (4:3)' },
				{ name: 'HD (1280 × 720 Pixel)' },
				{ name: 'Full HD (1920 × 1080 Pixel)' },
				{ name: '4K (3840 × 2160 Pixel)' },
				{ name: 'Instagram-Post (1080 × 1080)' },
				{ name: 'Facebook-Cover (820 × 312 Pixel)' },
				{ name: 'YouTube Thumbnail (1280 × 720 Pixel)' },
				{ name: 'LinkedIn Post (1200 × 627 Pixel)' },
				{ name: 'iPhone 15 Pro (2556 × 1179 Pixel)' },
				{ name: 'iPad Pro 12.9“ (2732 × 2048 Pixel)' },
			],
		},
		{
			name: 'Medium/Material',
			description: 'Geben Sie das Material bzw. die Art des Bildes an.',
			id: 'material-output',
			class: 'btn btn-outline-info',
			type: 'button',
			children: [
				{ name: 'Fotografie', description: 'Erstellung von Bildern durch Licht auf einem lichtempfindlichen Medium.' },
				{
					name: '\u00d6l auf Leinwand',
					description: 'Maltechnik mit \u00d6lfarben auf einer Leinwand als Trägermaterial.',
				},
				{
					name: 'Digitale Illustration',
					description: 'Erstellung von Kunstwerken mit digitalen Werkzeugen wie Tablets und Software.',
				},
				{
					name: 'Kohlezeichnung',
					description: 'Zeichnungen mit Kohle auf Papier, oft für Skizzen oder Schatteneffekte.',
				},
				{ name: 'Aquarell', description: 'Malerei mit transparenten Wasserfarben auf speziellem Aquarellpapier.' },
				{ name: 'Pastellkreide', description: 'Zeichnungen mit weichen, farbintensiven Kreiden auf rauem Papier.' },
				{
					name: 'Bleistiftzeichnung',
					description: 'Klassische Zeichnung oder Skizze mit Bleistift in unterschiedlichen Härtegraden.',
				},
				{
					name: 'Tuschezeichnung',
					description: 'Klare Linien und Schraffuren mit Tinte, oft für detailreiche Arbeiten verwendet.',
				},
				{
					name: 'Gouache',
					description: 'Deckende Wasserfarben, die kräftiger als Aquarell sind und leuchtend wirken.',
				},
				{
					name: 'Acrylmalerei',
					description: 'Schnelltrocknende Farben, die vielseitig auf unterschiedlichen Oberflächen angewendet werden.',
				},
				{
					name: 'Collage',
					description: 'Kunstwerke aus der Kombination von Papier, Fotos, Textilien und weiteren Materialien.',
				},
				{ name: 'Enkaustik', description: 'Maltechnik mit heißem Wachs und Farbpigmenten, meist auf Holzplatten.' },
				{
					name: 'Linolschnitt / Holzschnitt',
					description: 'Drucktechnik, bei der Motive aus Linoleum oder Holz geschnitten und gedruckt werden.',
				},
				{
					name: 'Spray-Art (Graffiti)',
					description: 'Bilder, die mit Sprayfarben auf Wänden, Leinwänden oder anderen Flächen entstehen.',
				},
				{
					name: 'Digital Painting',
					description: 'Digitale Malerei mit Software wie Photoshop oder Procreate und speziellen Pinseln.',
				},
				{
					name: 'Mischtechnik (Mixed Media)',
					description: 'Kombination verschiedener Materialien und Techniken in einem Kunstwerk.',
				},
				{
					name: 'Airbrush',
					description: 'Präziser Farbauftrag mit einer Spritzpistole für glatte Verlaufe und Details.',
				},
				{
					name: 'Kalligrafie',
					description: 'Kunstvolle Gestaltung von Schriftzeichen, oft kombiniert mit Zeichnungen.',
				},
				{ name: 'Sandkunst', description: 'Bilder oder Installationen, die durch die Verwendung von Sand entstehen.' },
				{
					name: 'Wachsfarben (Crayon)',
					description: 'Zeichnungen mit Wachsmalstiften, die farbintensiv und leicht zu verwenden sind.',
				},
				{ name: 'Metallgravur', description: 'Gravur von Bildern oder Mustern in Metall wie Kupfer oder Silber.' },
				{
					name: 'Glasmalerei',
					description: 'Farben und Bilder, die auf Glas angebracht oder in Glas integriert werden.',
				},
			],
		},
	],
}
